#ac6b1096ca56b9f6d004b779ae3728bf83f8e22453404cc3cef16a3d9b96608bc67c4b30db88e0a5a6c6390213f7acbe1153ff6d23ce57380104288ae19373ef



# The quorum deployment consists of
# 1. the transaction manager / private tx container (constellation or tessera)
# 2. the quorum node container

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quorum-node1-deployment
  
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      name: quorum-node1-deployment
  template:
    metadata:
      name:  quorum-node1-deployment
      labels:
        app: qubernetes
        tier: backend
        name: quorum-node1-deployment
    spec:
      securityContext:
      initContainers:
      - name: quorum-genesis-init-container
        image: quorumengineering/quorum:20.10.0
        command: [ "sh" ]
        args:
        - "-cx"
        - "if [ ! -f $QUORUM_DATA_DIR/genesis_created ]; then
              /usr/local/bin/geth --datadir $QUORUM_DATA_DIR init /etc/quorum/genesis/genesis-geth.json;
              date > $QUORUM_DATA_DIR/genesis_created;
           fi;
           cp -r /etc/quorum/qdata/contracts-tmp /etc/quorum/qdata/contracts;
           chmod 755  /etc/quorum/qdata/contracts/runscript.sh;
          "
        env:
          - name: QUORUM_DATA_DIR
            value: /etc/quorum/qdata/dd
          - name: QHOME
            value: /etc/quorum/qdata
        volumeMounts:
        - name: quorum-persistent-storage
          mountPath:  /etc/quorum/qdata
          subPath: quorum-node1
        - name: genesis-config-persistent-storage
          mountPath: /etc/quorum/genesis/genesis-geth.json
          subPath: genesis-geth.json
        - name: contracts-config
          mountPath: /etc/quorum/qdata/contracts-tmp
          readOnly: false
      containers:
      - name: constellation
        image:  quorumengineering/constellation:0.3.2
        command: ["sh"]
        args:
        - "-cx"
        - "chmod 600 $QUORUM_HOME/tm/tm.key;
           DDIR=$QUORUM_HOME/tm;
           printenv;
           args=\" --url=https://$QUORUM_NODE1_SERVICE_HOST:9001/  \
           --port=9001 \
           --workdir=$DDIR \
           --socket=$DDIR/tm.ipc \
           --publickeys=$QUORUM_HOME/tm/tm.pub \
           --privatekeys=$QUORUM_HOME/tm/tm.key \
           --verbosity=9 \
           --othernodes=https://$QUORUM_NODE1_SERVICE_HOST:9001/ \";
           /usr/local/bin/constellation-node $args  2>&1 | tee -a $QUORUM_HOME/logs/tm.log; "
        ports:
          - containerPort: 9001
        env:
          - name: QHOME
            value: /etc/quorum/qdata
          - name: QUORUM_HOME
            value: /etc/quorum/qdata
          - name: DDIR
            value: /etc/quorum/qdata/tm
        volumeMounts:
        - name: quorum-persistent-storage
          mountPath: /etc/quorum/qdata
          subPath: quorum-node1
        - name: quorum-persistent-storage
          mountPath: /etc/quorum/qdata/tm
          subPath: quorum-node1-tm
        - name: quorum-persistent-storage
          mountPath: /etc/quorum/qdata/logs
          subPath: quorum-node1-logs
        - name: keystore-tm
          mountPath: /etc/quorum/qdata/tm/tm.pub
          subPath: tm.pub
        - name: keystore-tm
          mountPath: /etc/quorum/qdata/tm/tm.key
          subPath: tm.key
      - name: quorum
        image: quorumengineering/quorum:20.10.0
        readinessProbe:
          exec:
            command:
              - ls
              - $(QHOME)/dd/geth.ipc
          initialDelaySeconds: 20
          periodSeconds: 3
        command: [ "sh" ]
        args:
        - "-cx"
        - "
           apk add jq;

           ln -s $QUORUM_HOME/permission-nodes/permissioned-nodes.json $QUORUM_DATA_DIR/permissioned-nodes.json;
           ln -s $QUORUM_HOME/permission-nodes/permissioned-nodes.json $QUORUM_DATA_DIR/static-nodes.json;

           rm -r /etc/quorum/qdata/contracts-tmp;
           cat /etc/quorum/genesis/genesis-geth.json;

           chmod 644 $QUORUM_DATA_DIR/keystore/key;
           sleep 5;
           echo slept for 5 to give TM time to start up;


           touch $QUORUM_DATA_DIR/password.txt;
           NETWORK_ID=10
           RPC_APIS=admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum
           args=\" --gcmode archive --raft  --raftport 50401 --raftdnsenable \";
           RPC_APIS=\"$RPC_APIS,raft\";
           args=\"$args --allow-insecure-unlock \";
           /usr/local/bin/geth \
           --datadir $QUORUM_DATA_DIR \
           $args \
           --permissioned \
           --nodiscover \
           --nat=none \
           --verbosity 9 \
           --networkid $NETWORK_ID \
           --unlock 0 \
           --emitcheckpoints \
           --rpc \
           --rpcaddr 0.0.0.0 \
           --rpcport 8545 \
           --rpcapi $RPC_APIS \
           --wsapi $RPC_APIS \
           --wsport 8546 \
           --port 30303 \
            \
           --password $QUORUM_DATA_DIR/password.txt 2>&1 | tee -a /etc/quorum/qdata/logs/quorum.log;"
        ports:
          - containerPort: 50401
          - containerPort: 8545
          - containerPort: 8546
          - containerPort: 30303
        
        env:
        - name: PRIVATE_CONFIG
          value: /etc/quorum/qdata/tm/tm.ipc
        - name: QUORUM_DATA_DIR
          value: /etc/quorum/qdata/dd
        - name: QUORUM_HOME
          value: /etc/quorum/qdata
        - name: QHOME
          value: /etc/quorum/qdata
        - name: TM_HOME
          value: /etc/quorum/qdata/tm/
        - name: THIS_NODE_ID
          value: quorum-node1
        - name: THIS_ENODE
          value: ac6b1096ca56b9f6d004b779ae3728bf83f8e22453404cc3cef16a3d9b96608bc67c4b30db88e0a5a6c6390213f7acbe1153ff6d23ce57380104288ae19373ef
        volumeMounts:
        - name: quorum-persistent-storage
          mountPath: /etc/quorum/qdata
          subPath: quorum-node1
        - name: quorum-persistent-storage
          mountPath: /etc/quorum/qdata/tm
          subPath: quorum-node1-tm
        - name: quorum-persistent-storage
          mountPath: /etc/quorum/qdata/logs
          subPath: quorum-node1-logs
        - name: genesis-config-persistent-storage
          mountPath: /etc/quorum/genesis/genesis-geth.json
          subPath: genesis-geth.json
        - name: quorum-key-config-persistent-storage
          mountPath: /etc/quorum/qdata/dd/keystore/key
          subPath: key
        - name: quorum-nodekey
          mountPath: /etc/quorum/qdata/dd/geth/nodekey
          subPath: nodekey
        - name: quorum-enode
          mountPath: /etc/quorum/qdata/dd/geth/enode
          subPath: enode
        - name: quorum-permissioned-config
          mountPath: /etc/quorum/qdata/permission-nodes
        - name: geth-helpers
          mountPath: /geth-helpers
        - name: node-management
          mountPath: /etc/quorum/qdata/node-management/raft_add_all_permissioned.sh
          subPath: raft_add_all_permissioned.sh
      volumes:
      - name: quorum-permissioned-config
        configMap:
          name: quorum-permissioned-config
          items:
          - key: permissioned-nodes.json
            path: permissioned-nodes.json
      - name: genesis-config-persistent-storage
        configMap:
          name: genesis-config
          items:
          - key: genesis-geth.json
            path: genesis-geth.json
      - name: tessera-config
        configMap:
          name: tessera-config
          items:
          - key: tessera-config.json.tmpl
            path: tessera-config.json.tmpl
          - key: tessera-config-enhanced.json.tmpl
            path: tessera-config-enhanced.json.tmpl
          - key: tessera-config-9.0.json.tmpl
            path: tessera-config-9.0.json.tmpl
      - name: contracts-config
        configMap:
          name: contracts-config
      - name: keystore-tm
        configMap:
          name: quorum-node1-tm-key-config
          items:
          - key: tm.pub
            path: tm.pub
          - key: tm.key
            path: tm.key
      - name: quorum-key-config-persistent-storage
        configMap:
          name: quorum-node1-account-key-config
          items:
          - key: key
            path: key
      - name: quorum-nodekey
        configMap:
          name: quorum-node1-nodekey-config
          items:
          - key: nodekey
            path: nodekey
      - name: quorum-enode
        configMap:
          name: quorum-node1-enode-config
          items:
            - key: enode
              path: enode
      - name: geth-helpers
        configMap:
          name: geth-helpers
          items:
            - key: geth-attach.sh
              path: geth-attach.sh
            - key: geth-exec.sh
              path: geth-exec.sh
          defaultMode: 0777
      - name: node-management
        configMap:
          name: node-management
          items:
            - key: raft_add_all_permissioned.sh
              path: raft_add_all_permissioned.sh
          defaultMode: 0777
      # PVC (configurable) https://kubernetes.io/docs/concepts/storage/persistent-volumes/#claims-as-volumes
      - name: quorum-persistent-storage
        persistentVolumeClaim:
          claimName: quorum-node1-pvc
