namespace:
  name: quorum-test
# number of nodes to deploy, this is relying on already generated files which reside in the 7nodes
# directory, so teh number will always be 7.
# see: 7nodes directory for already generated quorum resources and various qubernetes.yaml files.
nodes:
  number: 7 
quorum:
  # supported: (raft | istanbul)
  consensus: istanbul 
  # base quorum data dir as set inside each container.
  Node_DataDir: /etc/quorum/qdata
  # This is where all the keys are store, and/or where they are generated, as in the case of quorum-keygen.
  # Either full or relative paths on the machine generating the config
  Key_Dir_Base: 7nodes 
  Permissioned_Nodes_File: 7nodes/permissioned-nodes.json
  Genesis_File: 7nodes/istanbul-7nodes/istanbul-genesis.json
  # related to quorum containers
  quorum:
    Raft_Port: 50401
    # container images at https://hub.docker.com/u/quorumengineering/
    Quorum_Version: 2.2.3
  # related to transaction manager containers
  tm:
    # container images at https://hub.docker.com/u/quorumengineering/
    #       in that case.
    Tm_Version: 0.3.2
    Port: 9001

# generic geth related options
geth:
  Node_WSPort: 8546
  NodeP2P_ListenAddr: 21000 
  network:
    # network id (1: mainnet, 3: ropsten, 4: rinkeby ... )
    id: 1101
    # public (true|false) is it a public network?
    public: false
  # general verbosity of geth [1..5]
  verbosity: 9
